name: auth_repo
description: A sample command-line application.
version: 1.0.0
publish_to: none
# homepage: https://www.example.com

environment:
  sdk: '>=2.17.1 <3.0.0'

dependencies:
  mem_cache:
    path: ../mem_cache
  firebase_auth: ^3.3.18
  equatable: ^2.0.3

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
